export default [{
  packageName: 'highchart-curve',
  packageLabel: 'HighChart风格曲线',
  components: [{
    name: 'shapea',
    label: '单曲线图',
    preview: 'https://10.10.3.12:4899/scada/npm_packages/@gw/apollo-standard-charts/previews/standardNestedRing.svg'
  }, {
    name: 'shapeb',
    label: '单折线图',
    preview: 'https://10.10.3.12:4899/scada/npm_packages/@gw/apollo-standard-charts/previews/standardNestedRing.svg'
  }, {
    name: 'shapec',
    label: '多曲线图',
    preview: 'https://10.10.3.12:4899/scada/npm_packages/@gw/apollo-standard-charts/previews/standardNestedRing.svg'
  }, {
    name: 'shaped',
    label: '多折线图',
    preview: 'https://10.10.3.12:4899/scada/npm_packages/@gw/apollo-standard-charts/previews/standardNestedRing.svg'
  }, {
    name: 'shapee',
    label: '单饼图',
    preview: 'https://10.10.3.12:4899/scada/npm_packages/@gw/apollo-standard-charts/previews/standardNestedRing.svg'
  }]
}, {
  packageName: 'basic',
  packageLabel: '基础图元',
  components: [{
    name: 'shapea',
    label: '矩形框',
    preview: 'https://10.10.3.12:4899/scada/npm_packages/@gw/apollo-standard-charts/previews/standardNestedRing.svg'
  }, {
    name: 'shapeb',
    label: '文本',
    preview: 'https://10.10.3.12:4899/scada/npm_packages/@gw/apollo-standard-charts/previews/standardNestedRing.svg'
  }, {
    name: 'shapec',
    label: '多曲线图',
    preview: 'https://10.10.3.12:4899/scada/npm_packages/@gw/apollo-standard-charts/previews/standardNestedRing.svg'
  }, {
    name: 'shaped',
    label: '多折线图',
    preview: 'https://10.10.3.12:4899/scada/npm_packages/@gw/apollo-standard-charts/previews/standardNestedRing.svg'
  }, {
    name: 'shapee',
    label: '单饼图',
    preview: 'https://10.10.3.12:4899/scada/npm_packages/@gw/apollo-standard-charts/previews/standardNestedRing.svg'
  }]
}]